name: bbb

on:
  push:
    tags:
      - 'v[0-9]+'
      
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.sha }}"
          echo "12345"

      - 
        run: |
        
          x=$( \
            curl \
            -sS \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/git/refs/heads/main" \
          )
          
          echo $x
