name: bbb

on:
  push:
    tags:
      - 'v[0-9]+'
      
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.sha }}"
          echo "12345"

      - run: |
        git rev-parse origin/main

