name: test

on:
  push:
  
  pull_request:
    branches:
      - main
    types: [opened, synchronize, repoened]
    

jobs:

  #pull_requestの存在確認
  job1:
    runs-on: ubuntu-latest
    
    outputs:
      run_ci: ${{ steps.step1.outputs.run_ci }}
      
    steps:
      - 
        id: step1
        run: |
          echo "------------------------------------------"
          echo "job1"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          echo "GITHUB_REF        = $GITHUB_REF"
          echo "GITHUB_REF_NAME   = $GITHUB_REF_NAME"
          echo "------------------------------------------"
          echo "GITHUB_EVENT_NAME   = $GITHUB_EVENT_NAME"
          echo "github.event.action = ${{github.event.action}}"
          echo "------------------------------------------"
          
          if [[ "${{github.event_name}}" == "push" && "${{ github.ref_name }}" != "main" ]]; then
            
            PR=$(\
              curl \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=open&head=$GITHUB_REPOSITORY:$GITHUB_REF_NAME" \
            )
            echo $PR
            
            if echo "$PR" | jq -e 'if type == "array" then true else false end'; then

              # 配列の場合、要素数が0かどうかをチェック
              RUN_CI=$(echo "$PR" | jq -r 'if . | length == 0 then true else false end')
            else

              # 配列ではない場合(正しくプルリクが取得できていない)
              exit 1
            fi
            
          else
          
            RUN_CI="true"
          
          fi
          
          echo "run_ci=$RUN_CI" >> $GITHUB_OUTPUT
          echo "run_ci=<<<$RUN_CI>>>"

  #静的解析
  job2:
    needs: job1
    if: needs.job1.outputs.run_ci == 'true'
    uses: ./.github/workflows/ci.yml

#  job2:
#    runs-on: ubuntu-latest
#    needs: job1
#    if: needs.job1.outputs.pr_exists == 'true'
#    steps:
#      - run: |
#          echo "job2"
#          echo "${{needs.job1.outputs.pr_exists}}"




  #デプロイ
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job3"
