name: test

on:
  push:
  
  pull_request:
    branches:
      - main
    

jobs:

  #pull_requestの確認
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job1"
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_REF_NAME"
          echo "$GITHUB_REF"

          echo "$GITHUB_EVENT_NAME"
          echo "${{github.event.action}}"
          
          PR=$(\
            curl \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -s \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=open&head=$GITHUB_REPOSITORY:$GITHUB_REF_NAME" \
          )
          echo $PR
          PR_EXISTS=$(echo "$PR" | jq -r '. | length > 0')
          echo $PR_EXISTS


  #静的解析
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "job2"

  #デプロイ
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: |
          echo "job3"
