name: test

on:
  push:
  
  pull_request:
    branches:
      - main
    

jobs:

  #pull_requestの確認
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job1"
          echo "${{github.ref_name}}"
          echo "$GITHUB_REF_NAME"
          echo "${{github.ref}}"
          echo "$GITHUB_REF"

  #静的解析
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job2"

  #デプロイ
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job3"
